export const LoaderConfig = {
    Background: "src/sprites/Background.jpg",
    reelBg: "src/sprites/reelBg.png",
    gameBg: "src/sprites/Background.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover_1.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed : "/src/sprites/ButtonAutoSpinHover_1.png",
    BetPanel :  "/src/sprites/PanelTotalBet.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/PanelLines.png",
    winPanel :  "/src/sprites/winPanel.png",      
    balancePanel :  "/src/sprites/PanelBalance.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png", 
    settingHeading: "src/sprites/SettingPopupBg.png",
    mafiaLogo: "src/sprites/mafiaLogo.png",
    numOfLines: "src/sprites/numberofLines.png",


    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButtonHover.png",
    messagePopup: "src/sprites/messagePopup.png",
    winTableBg: "src/sprites/winTableBg.jpg",
    leftArrow: "src/sprites/leftArrow.png",
    rightArrow: "src/sprites/rightArrow.png",
    winTableHeading: "src/sprites/winTableHeading.png",
    prefix: "src/sprites/prefix.png",

    inofIcon1: "src/sprites/inofIcon1.png",
    inofIcon2: "src/sprites/inofIcon2.png",
    inofIcon3: "src/sprites/inofIcon3.png",
    inofIcon4: "src/sprites/inofIcon4.png",
    inofIcon5: "src/sprites/inofIcon5.png",
    inofIcon6: "src/sprites/inofIcon6.png",
    inofIcon7: "src/sprites/inofIcon7.png",
    inofIcon8: "src/sprites/inofIcon8.png",
    inofIcon9: "src/sprites/inofIcon9.png",
    inofIcon10: "src/sprites/inofIcon10.png",
    inofIcon11: "src/sprites/inofIcon11.png",
    inofIcon12: "src/sprites/inofIcon12.png",
    
    disconnectClose: "src/sprites/CloseButton.png",
    SoundtoggleOff: "src/sprites/toggleOff.png",
    SoundtoggleOn: "src/sprites/toggleOn.png",
    MusictoggleOff: "src/sprites/toggleOff.png",
    MusictoggleOn: "src/sprites/toggleOn.png",
    SoundToggleBg: "src/sprites/SoundToggleBg.png",
    SOUNDS: "src/sprites/soundText.png",
    MUSIC: "src/sprites/musicText.png",
    settingText: "src/sprites/SettingsText.png",

    headingImage: "src/sprites/PayTable.png",
    scrollBg: "src/sprites/ScrollBar.png",
    scroller:"src/sprites/Roller.png",
    minorSymbolsHeading: "src/sprites/MinorSymbols.png",
    majorSymbolHeading: "src/sprites/MajorSymbolsHeading.png",
    specialSymBolHeading: "src/sprites/SpecialSymbolHeading.png",
    payLines: "src/sprites/PayLines.png",
    payLinesHeading: "src/sprites/PayLinesHeading.png",
    bigWinPopup:"src/sprites/bigWinPopup.png",
    hugeWinPopup: "src/sprites/hugeWinPopup.png",
    megaWinPopup: "src/sprites/megaWinPopup.png",
    jackpotPopup: "src/sprites/jackpotPopup.png",

    yesButton:"src/sprites/yesButton.png",
    yesButtonHover: "src/sprites/yesButtonHover.png",
    noButton:"src/sprites/noButton.png",
    noButtonHover:"src/sprites/noButtonHover.png",
    sounProgress: "src/sprites/soundProgreesBar.png",

    left0: "src/sprites/1.png",
    left1: "src/sprites/2.png",
    left2: "src/sprites/3.png",
    left3: "src/sprites/4.png",
    left4: "src/sprites/5.png",
    left5: "src/sprites/6.png",
    left6: "src/sprites/7.png",
    left7: "src/sprites/8.png",
    left8: "src/sprites/9.png",

    right0: "src/sprites/1.png",
    right1: "src/sprites/2.png",
    right2: "src/sprites/3.png",
    right3: "src/sprites/4.png",
    right4: "src/sprites/5.png",
    right5: "src/sprites/6.png",
    right6: "src/sprites/7.png",
    right7: "src/sprites/8.png",
    right8: "src/sprites/9.png",

    slots0_0 : "/src/sprites/Symbols/icon1/A1.png",
    slots0_1 : "/src/sprites/Symbols/icon1/A2.png",
    slots0_2 : "/src/sprites/Symbols/icon1/A3.png",
    slots0_3 : "/src/sprites/Symbols/icon1/A4.png",
    slots0_4 : "/src/sprites/Symbols/icon1/A5.png",
    slots0_5 : "/src/sprites/Symbols/icon1/A6.png",
    slots0_6 : "/src/sprites/Symbols/icon1/A7.png",
    slots0_7 : "/src/sprites/Symbols/icon1/A8.png",
    slots0_8 : "/src/sprites/Symbols/icon1/A9.png",
    slots0_9 : "/src/sprites/Symbols/icon1/A10.png",
    slots0_10 : "/src/sprites/Symbols/icon1/A11.png",
    slots0_11 : "/src/sprites/Symbols/icon1/A12.png",
    slots0_12 : "/src/sprites/Symbols/icon1/A13.png",
    slots0_13 : "/src/sprites/Symbols/icon1/A14.png",
    slots0_14 : "/src/sprites/Symbols/icon1/A15.png",
    slots0_15 : "/src/sprites/Symbols/icon1/A16.png",
    slots0_16 : "/src/sprites/Symbols/icon1/A17.png",
    slots0_17 : "/src/sprites/Symbols/icon1/A18.png",
    slots0_18 : "/src/sprites/Symbols/icon1/A19.png",
    slots0_19 : "/src/sprites/Symbols/icon1/A20.png",
    slots0_20 : "/src/sprites/Symbols/icon1/A21.png",
    slots0_21 : "/src/sprites/Symbols/icon1/A22.png",
    slots0_22 : "/src/sprites/Symbols/icon1/A23.png",
    slots0_23 : "/src/sprites/Symbols/icon1/A24.png",


    slots1_0 : "/src/sprites/Symbols/icon2/K1.png",
    slots1_1:  "/src/sprites/Symbols/icon2/K2.png",
    slots1_2:  "/src/sprites/Symbols/icon2/K3.png",
    slots1_3:  "/src/sprites/Symbols/icon2/K4.png",
    slots1_4:  "/src/sprites/Symbols/icon2/K5.png",
    slots1_5:  "/src/sprites/Symbols/icon2/K6.png",
    slots1_6:  "/src/sprites/Symbols/icon2/K7.png",
    slots1_7 : "/src/sprites/Symbols/icon2/K8.png",
    slots1_8 : "/src/sprites/Symbols/icon2/K9.png",
    slots1_9 : "/src/sprites/Symbols/icon2/K10.png",
    slots1_10 : "/src/sprites/Symbols/icon2/K11.png",
    slots1_11 : "/src/sprites/Symbols/icon2/K12.png",
    slots1_12 : "/src/sprites/Symbols/icon2/K13.png",
    slots1_13 : "/src/sprites/Symbols/icon2/K14.png",
    slots1_14 : "/src/sprites/Symbols/icon2/K15.png",
    slots1_15 : "/src/sprites/Symbols/icon2/K16.png",
    slots1_16 : "/src/sprites/Symbols/icon2/K17.png",
    slots1_17 : "/src/sprites/Symbols/icon2/K18.png",
    slots1_18 : "/src/sprites/Symbols/icon2/K19.png",
    slots1_19 : "/src/sprites/Symbols/icon2/K20.png",
    slots1_20 : "/src/sprites/Symbols/icon2/K21.png",
    slots1_21 : "/src/sprites/Symbols/icon2/K22.png",
    slots1_22 : "/src/sprites/Symbols/icon2/K23.png",
    slots1_23 : "/src/sprites/Symbols/icon2/K24.png",

    slots2_0 :  "/src/sprites/Symbols/icon3/Q1.png",
    slots2_1 : "/src/sprites/Symbols/icon3/Q2.png",
    slots2_2 : "/src/sprites/Symbols/icon3/Q3.png",
    slots2_3 : "/src/sprites/Symbols/icon3/Q4.png",
    slots2_4 : "/src/sprites/Symbols/icon3/Q5.png",
    slots2_5 : "/src/sprites/Symbols/icon3/Q6.png",
    slots2_6 : "/src/sprites/Symbols/icon3/Q7.png",
    slots2_7 : "/src/sprites/Symbols/icon3/Q8.png",
    slots2_8 : "/src/sprites/Symbols/icon3/Q9.png",
    slots2_9 : "/src/sprites/Symbols/icon3/Q10.png",
    slots2_10 : "/src/sprites/Symbols/icon3/Q11.png",
    slots2_11 : "/src/sprites/Symbols/icon3/Q12.png",
    slots2_12 : "/src/sprites/Symbols/icon3/Q13.png",
    slots2_13 : "/src/sprites/Symbols/icon3/Q14.png",
    slots2_14 : "/src/sprites/Symbols/icon3/Q15.png",
    slots2_15 : "/src/sprites/Symbols/icon3/Q16.png",
    slots2_16 : "/src/sprites/Symbols/icon3/Q17.png",
    slots2_17 : "/src/sprites/Symbols/icon3/Q18.png",
    slots2_18 : "/src/sprites/Symbols/icon3/Q19.png",
    slots2_19 : "/src/sprites/Symbols/icon3/Q20.png",
    slots2_20 : "/src/sprites/Symbols/icon3/Q21.png",
    slots2_21 : "/src/sprites/Symbols/icon3/Q21.png",
    slots2_22 : "/src/sprites/Symbols/icon3/Q22.png",
    slots2_23 : "/src/sprites/Symbols/icon3/Q23.png",


    slots3_0 :  "/src/sprites/Symbols/icon4/J1.png",
    slots3_1 :  "/src/sprites/Symbols/icon4/J2.png",
    slots3_2 :  "/src/sprites/Symbols/icon4/J3.png",
    slots3_3 :  "/src/sprites/Symbols/icon4/J4.png",
    slots3_4 :  "/src/sprites/Symbols/icon4/J5.png",
    slots3_5 :  "/src/sprites/Symbols/icon4/J6.png",
    slots3_6 :  "/src/sprites/Symbols/icon4/J7.png",
    slots3_7 :  "/src/sprites/Symbols/icon4/J8.png",
    slots3_8 :  "/src/sprites/Symbols/icon4/J9.png",
    slots3_9 :  "/src/sprites/Symbols/icon4/J10.png",
    slots3_10 :  "/src/sprites/Symbols/icon4/J11.png",
    slots3_11 :  "/src/sprites/Symbols/icon4/J12.png",
    slots3_12 :  "/src/sprites/Symbols/icon4/J13.png",
    slots3_13 :  "/src/sprites/Symbols/icon4/J14.png",
    slots3_14 :  "/src/sprites/Symbols/icon4/J15.png",
    slots3_15 :  "/src/sprites/Symbols/icon4/J16.png",
    slots3_16 : "/src/sprites/Symbols/icon4/J17.png",
    slots3_17 : "/src/sprites/Symbols/icon4/J18.png",
    slots3_18 : "/src/sprites/Symbols/icon4/J19.png",
    slots3_19 : "/src/sprites/Symbols/icon4/J20.png",
    slots3_20 : "/src/sprites/Symbols/icon4/J21.png",
    slots3_21 : "/src/sprites/Symbols/icon4/J22.png",
    slots3_22 : "/src/sprites/Symbols/icon4/J23.png",
    slots3_23 : "/src/sprites/Symbols/icon4/J24.png",

    slots4_0 :  "/src/sprites/Symbols/icon5/101.png",
    slots4_1 :  "/src/sprites/Symbols/icon5/102.png",
    slots4_2 :  "/src/sprites/Symbols/icon5/103.png",
    slots4_3 :  "/src/sprites/Symbols/icon5/104.png",
    slots4_4 :  "/src/sprites/Symbols/icon5/105.png",
    slots4_5 :  "/src/sprites/Symbols/icon5/106.png",
    slots4_6 :  "/src/sprites/Symbols/icon5/107.png",
    slots4_7 :  "/src/sprites/Symbols/icon5/108.png",
    slots4_8 :  "/src/sprites/Symbols/icon5/109.png",
    slots4_9 :  "/src/sprites/Symbols/icon5/1010.png",
    slots4_10 :  "/src/sprites/Symbols/icon5/1011.png",
    slots4_11 :  "/src/sprites/Symbols/icon5/1012.png",
    slots4_12 :  "/src/sprites/Symbols/icon5/1013.png",
    slots4_13 :  "/src/sprites/Symbols/icon5/1014.png",
    slots4_14 :  "/src/sprites/Symbols/icon5/1015.png",
    slots4_15 :  "/src/sprites/Symbols/icon5/1016.png",
    slots4_16 : "/src/sprites/Symbols/icon5/1017.png",
    slots4_17 : "/src/sprites/Symbols/icon5/1018.png",
    slots4_18 : "/src/sprites/Symbols/icon5/1019.png",
    slots4_19 : "/src/sprites/Symbols/icon5/1020.png",
    slots4_20 : "/src/sprites/Symbols/icon5/1021.png",
    slots4_21 : "/src/sprites/Symbols/icon5/1022.png",
    slots4_22 : "/src/sprites/Symbols/icon5/1023.png",
    slots4_23 : "/src/sprites/Symbols/icon5/1024.png",

    slots5_0 :  "/src/sprites/Symbols/icon6/Slots601.png",
    slots5_1 :  "/src/sprites/Symbols/icon6/Slots602.png",
    slots5_2 :  "/src/sprites/Symbols/icon6/Slots603.png",
    slots5_3 :  "/src/sprites/Symbols/icon6/Slots604.png",
    slots5_4 :  "/src/sprites/Symbols/icon6/Slots605.png",
    slots5_5 :  "/src/sprites/Symbols/icon6/Slots606.png",
    slots5_6 :  "/src/sprites/Symbols/icon6/Slots607.png",
    slots5_7 :  "/src/sprites/Symbols/icon6/Slots608.png",
    slots5_8 :  "/src/sprites/Symbols/icon6/Slots609.png",
    slots5_9 :  "/src/sprites/Symbols/icon6/Slots610.png",
    slots5_10 : "/src/sprites/Symbols/icon6/Slots611.png",
    slots5_11 : "/src/sprites/Symbols/icon6/Slots612.png",
    slots5_12 : "/src/sprites/Symbols/icon6/Slots613.png",
    slots5_13 : "/src/sprites/Symbols/icon6/Slots614.png",
    slots5_14 : "/src/sprites/Symbols/icon6/Slots615.png",
    slots5_15 : "/src/sprites/Symbols/icon6/Slots616.png",
    slots5_16 : "/src/sprites/Symbols/icon6/Slots617.png",
    slots5_17 : "/src/sprites/Symbols/icon6/Slots618.png",
    slots5_18 : "/src/sprites/Symbols/icon6/Slots619.png",
    slots5_19 : "/src/sprites/Symbols/icon6/Slots620.png",
    slots5_20 : "/src/sprites/Symbols/icon6/Slots621.png",
    slots5_21 : "/src/sprites/Symbols/icon6/Slots622.png",
    slots5_22 : "/src/sprites/Symbols/icon6/Slots623.png",
    slots5_23 : "/src/sprites/Symbols/icon6/Slots624.png",

    slots6_0 :  "/src/sprites/Symbols/icon7/Slots701.png",
    slots6_1 :  "/src/sprites/Symbols/icon7/Slots702.png",
    slots6_2 :  "/src/sprites/Symbols/icon7/Slots703.png",
    slots6_3 :  "/src/sprites/Symbols/icon7/Slots704.png",
    slots6_4 :  "/src/sprites/Symbols/icon7/Slots705.png",
    slots6_5 :  "/src/sprites/Symbols/icon7/Slots706.png",
    slots6_6 :  "/src/sprites/Symbols/icon7/Slots707.png",
    slots6_7 :  "/src/sprites/Symbols/icon7/Slots708.png",
    slots6_8 :  "/src/sprites/Symbols/icon7/Slots709.png",
    slots6_9 :  "/src/sprites/Symbols/icon7/Slots710.png",
    slots6_10 :  "/src/sprites/Symbols/icon7/Slots711.png",
    slots6_11 :  "/src/sprites/Symbols/icon7/Slots712.png",
    slots6_12 :  "/src/sprites/Symbols/icon7/Slots713.png",
    slots6_13 :  "/src/sprites/Symbols/icon7/Slots714.png",
    slots6_14 :  "/src/sprites/Symbols/icon7/Slots715.png",
    slots6_15 :  "/src/sprites/Symbols/icon7/Slots716.png",
    slots6_16 : "/src/sprites/Symbols/icon7/Slots717.png",
    slots6_17 : "/src/sprites/Symbols/icon7/Slots718.png",
    slots6_18 : "/src/sprites/Symbols/icon7/Slots719.png",
    slots6_19 : "/src/sprites/Symbols/icon7/Slots720.png",
    slots6_20 : "/src/sprites/Symbols/icon7/Slots721.png",
    slots6_21 : "/src/sprites/Symbols/icon7/Slots722.png",
    slots6_22 : "/src/sprites/Symbols/icon7/Slots723.png",
    slots6_23 : "/src/sprites/Symbols/icon7/Slots724.png",


    slots7_0 :  "/src/sprites/Symbols/icon8/Slots801.png",
    slots7_1 :  "/src/sprites/Symbols/icon8/Slots802.png",
    slots7_2 :  "/src/sprites/Symbols/icon8/Slots803.png",
    slots7_3 :  "/src/sprites/Symbols/icon8/Slots804.png",
    slots7_4 :  "/src/sprites/Symbols/icon8/Slots805.png",
    slots7_5 :  "/src/sprites/Symbols/icon8/Slots806.png",
    slots7_6 :  "/src/sprites/Symbols/icon8/Slots807.png",
    slots7_7 :  "/src/sprites/Symbols/icon8/Slots808.png",
    slots7_8 :  "/src/sprites/Symbols/icon8/Slots809.png",
    slots7_9 :  "/src/sprites/Symbols/icon8/Slots810.png",
    slots7_10 :  "/src/sprites/Symbols/icon8/Slots811.png",
    slots7_11 :  "/src/sprites/Symbols/icon8/Slots812.png",
    slots7_12 :  "/src/sprites/Symbols/icon8/Slots813.png",
    slots7_13 :  "/src/sprites/Symbols/icon8/Slots814.png",
    slots7_14 :  "/src/sprites/Symbols/icon8/Slots815.png",
    slots7_15 :  "/src/sprites/Symbols/icon8/Slots816.png",
    slots7_16 : "/src/sprites/Symbols/icon8/Slots817.png",
    slots7_17 : "/src/sprites/Symbols/icon8/Slots818.png",
    slots7_18 : "/src/sprites/Symbols/icon8/Slots819.png",
    slots7_19 : "/src/sprites/Symbols/icon8/Slots820.png",
    slots7_20 : "/src/sprites/Symbols/icon8/Slots821.png",
    slots7_21 : "/src/sprites/Symbols/icon8/Slots822.png",
    slots7_22 : "/src/sprites/Symbols/icon8/Slots823.png",
    slots7_23 : "/src/sprites/Symbols/icon8/Slots824.png",

    slots8_0 : "/src/sprites/Symbols/icon9/bomb1.png",
    slots8_1 : "/src/sprites/Symbols/icon9/bomb2.png",
    slots8_2 : "/src/sprites/Symbols/icon9/bomb3.png",
    slots8_3 : "/src/sprites/Symbols/icon9/bomb4.png",
    slots8_4 : "/src/sprites/Symbols/icon9/bomb5.png",
    slots8_5 : "/src/sprites/Symbols/icon9/bomb6.png",
    slots8_6 : "/src/sprites/Symbols/icon9/bomb7.png",
    slots8_7 : "/src/sprites/Symbols/icon9/bomb8.png",
    slots8_8 : "/src/sprites/Symbols/icon9/bomb9.png",
    slots8_9 : "/src/sprites/Symbols/icon9/bomb10.png",
    slots8_10 : "/src/sprites/Symbols/icon9/bomb11.png",
    slots8_11 : "/src/sprites/Symbols/icon9/bomb12.png",
    slots8_12 : "/src/sprites/Symbols/icon9/bomb13.png",
    slots8_13 : "/src/sprites/Symbols/icon9/bomb14.png",
    slots8_14 : "/src/sprites/Symbols/icon9/bomb15.png",
    slots8_15 : "/src/sprites/Symbols/icon9/bomb16.png",
    slots8_16 : "/src/sprites/Symbols/icon9/bomb17.png",
    slots8_17 : "/src/sprites/Symbols/icon9/bomb18.png",
    slots8_18 : "/src/sprites/Symbols/icon9/bomb19.png",
    slots8_19 : "/src/sprites/Symbols/icon9/bomb20.png",
    slots8_20 : "/src/sprites/Symbols/icon9/bomb21.png",
    slots8_21 : "/src/sprites/Symbols/icon9/bomb22.png",
    slots8_22 : "/src/sprites/Symbols/icon9/bomb23.png",
    slots8_23 : "/src/sprites/Symbols/icon9/bomb24.png",

    slots9_0 : "/src/sprites/Symbols/icon10/wild1.png",
    slots9_1 : "/src/sprites/Symbols/icon10/wild2.png",
    slots9_2 : "/src/sprites/Symbols/icon10/wild3.png",
    slots9_3 : "/src/sprites/Symbols/icon10/wild4.png",
    slots9_4 : "/src/sprites/Symbols/icon10/wild5.png",
    slots9_5 : "/src/sprites/Symbols/icon10/wild6.png",
    slots9_6 : "/src/sprites/Symbols/icon10/wild7.png",
    slots9_7 : "/src/sprites/Symbols/icon10/wild8.png",
    slots9_8 : "/src/sprites/Symbols/icon10/wild9.png",
    slots9_9 : "/src/sprites/Symbols/icon10/wild10.png",
    slots9_10 : "/src/sprites/Symbols/icon10/wild11.png",
    slots9_11 : "/src/sprites/Symbols/icon10/wild12.png",
    slots9_12 : "/src/sprites/Symbols/icon10/wild13.png",
    slots9_13 : "/src/sprites/Symbols/icon10/wild14.png",
    slots9_14 : "/src/sprites/Symbols/icon10/wild15.png",
    slots9_15 : "/src/sprites/Symbols/icon10/wild16.png",
    slots9_16 : "/src/sprites/Symbols/icon10/wild17.png",
    slots9_17 : "/src/sprites/Symbols/icon10/wild18.png",
    slots9_18 : "/src/sprites/Symbols/icon10/wild19.png",
    slots9_19 : "/src/sprites/Symbols/icon10/wild20.png",
    slots9_20 : "/src/sprites/Symbols/icon10/wild21.png",
    slots9_21 : "/src/sprites/Symbols/icon10/wild22.png",
    slots9_22 : "/src/sprites/Symbols/icon10/wild23.png",
    slots9_23 : "/src/sprites/Symbols/icon10/wild24.png",

    slots10_0 : "/src/sprites/Symbols/icon11/Scatter1.png",
    slots10_1 : "/src/sprites/Symbols/icon11/Scatter2.png",
    slots10_2 : "/src/sprites/Symbols/icon11/Scatter3.png",
    slots10_3 : "/src/sprites/Symbols/icon11/Scatter4.png",
    slots10_4 : "/src/sprites/Symbols/icon11/Scatter5.png",
    slots10_5 : "/src/sprites/Symbols/icon11/Scatter6.png",
    slots10_6 : "/src/sprites/Symbols/icon11/Scatter7.png",
    slots10_7 : "/src/sprites/Symbols/icon11/Scatter8.png",
    slots10_8 : "/src/sprites/Symbols/icon11/Scatter9.png",
    slots10_9 : "/src/sprites/Symbols/icon11/Scatter10.png",
    slots10_10 : "/src/sprites/Symbols/icon11/Scatter11.png",
    slots10_11 : "/src/sprites/Symbols/icon11/Scatter12.png",
    slots10_12 : "/src/sprites/Symbols/icon11/Scatter13.png",
    slots10_13 : "/src/sprites/Symbols/icon11/Scatter14.png",
    slots10_14 : "/src/sprites/Symbols/icon11/Scatter15.png",
    slots10_15 : "/src/sprites/Symbols/icon11/Scatter16.png",
    slots10_16 : "/src/sprites/Symbols/icon11/Scatter17.png",
    slots10_17 : "/src/sprites/Symbols/icon11/Scatter18.png",
    slots10_18 : "/src/sprites/Symbols/icon11/Scatter19.png",
    slots10_19 : "/src/sprites/Symbols/icon11/Scatter20.png",
    slots10_20 : "/src/sprites/Symbols/icon11/Scatter21.png",
    slots10_21 : "/src/sprites/Symbols/icon11/Scatter22.png",
    slots10_22 : "/src/sprites/Symbols/icon11/Scatter23.png",
    slots10_23 : "/src/sprites/Symbols/icon11/Scatter24.png",

    slots11_0 : "/src/sprites/Symbols/icon12/money1.png",
    slots11_1 : "/src/sprites/Symbols/icon12/money2.png",
    slots11_2 : "/src/sprites/Symbols/icon12/money3.png",
    slots11_3 : "/src/sprites/Symbols/icon12/money4.png",
    slots11_4 : "/src/sprites/Symbols/icon12/money5.png",
    slots11_5 : "/src/sprites/Symbols/icon12/money6.png",
    slots11_6 : "/src/sprites/Symbols/icon12/money7.png",
    slots11_7 : "/src/sprites/Symbols/icon12/money8.png",
    slots11_8 : "/src/sprites/Symbols/icon12/money9.png",
    slots11_9 : "/src/sprites/Symbols/icon12/money10.png",
    slots11_10 : "/src/sprites/Symbols/icon12/money11.png",
    slots11_11 : "/src/sprites/Symbols/icon12/money12.png",
    slots11_12 : "/src/sprites/Symbols/icon12/money13.png",
    slots11_13 : "/src/sprites/Symbols/icon12/money14.png",
    slots11_14 : "/src/sprites/Symbols/icon12/money15.png",
    slots11_15 : "/src/sprites/Symbols/icon12/money16.png",
    slots11_16 : "/src/sprites/Symbols/icon12/money17.png",
    slots11_17 : "/src/sprites/Symbols/icon12/money18.png",
    slots11_18 : "/src/sprites/Symbols/icon12/money19.png",
    slots11_19 : "/src/sprites/Symbols/icon12/money20.png",
    slots11_20 : "/src/sprites/Symbols/icon12/money21.png",
    slots11_21 : "/src/sprites/Symbols/icon12/money22.png",
    slots11_22 : "/src/sprites/Symbols/icon12/money23.png",
    slots11_23 : "/src/sprites/Symbols/icon12/money24.png",

    line0: "src/sprites/line1.png",
    line1: "src/sprites/line2.png",
    line2: "src/sprites/line3.png",
    line3: "src/sprites/line4.png",
    line4: "src/sprites/line5.png",
    line5: "src/sprites/line6.png",
    line6: "src/sprites/line7.png",
    line7: "src/sprites/line8.png",
    line8: "src/sprites/line9.png",

    megawinAnimBg: "src/sprites/rays.png",
    megawinStar: "src/sprites/stars.png",
}

export const staticData = {
    Background:  "src/sprites/Background.jpg",
};

export const fontData = {
    crashLandingItalic : "src/fonts/RobotoSlab-Bold.ttf"
}

export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.wav",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.wav",
        buttonpressed: "src/sounds/Game-Button.mp3",
 
};
